### ISSUE TITLE
when using Echo360 users are restricted to size of 600px

### ISSUE THREAD

**Issue by Fae6068123** [PlaneteStream/moodle-assignsubmission_estream#10]
I noticed that Echo360 videos added via External tool are an odd size. The container size looks to currently be  height="600px" width="100%". Could the height be increased to improve the appearance? 
![image-2021-10-26-14-59-30-643](https://user-images.githubusercontent.com/59917516/141282599-b2c958b9-b33a-4dc6-a818-9132ab7a2d4c.png)

**Comment by PlaneteStream** [comment]
Hi @Fae6068123 ,

Was this message meant to be posted on the Echo360 Github rather than the Planet eStream one? Please let us know if there's something we're missing, thank you.
