### ISSUE TITLE
When using eStream the footer is appearing at a fixed point on the background.  

### ISSUE THREAD

**Issue by Fae6068123** [PlaneteStream/moodle-assignsubmission_estream#11]
This issue affects the position of the footnote. When testing video upload using e-Stream, with the standard Default Boost moodle theme, classic, etc. it appears that the footnote is incorrectly placed to the background at a fixed location. This is incorrect. the footnote should appear at the bottom of the screen. This issue is consistent with a known bug in e-Stream reported

**Comment by PlaneteStream** [comment]
Hi there,

We have very recently been trying to improve this part of the UI on mobile devices; Moodle has a history of not being especially well formatted on mobile devices, but recent updates seem to have improved this. If you update your plugin files you may find that this is now improved on default Moodle themes - however, in custom themes this may not be the case.
