### ISSUE TITLE
When using eStream the footer is appearing at a fixed point on the background.

### ISSUE THREAD

**Issue by Fae6068123** [PlaneteStream/moodle-assignsubmission_estream#12]
The problem of the footnote appearing half way down the screen is appearing also on Moodle base theme. It appears that the plugin is overiding a setting to push to the bottom of the screen and re-display center of screen.

**Comment by Fae6068123** [comment]
The problem is observed across all mobile devices.

**Comment by PlaneteStream** [comment]
Hi @Fae6068123,

Could you confirm that you're using the latest version of the locallib.php file? We made some changes in September 2021 that seemed to resolve this issue in the base theme on desktop and mobile. Please let us know if you're using an up-to-date file and still having the same problem.

**Comment by Fae6068123** [comment]
Which version should be used?

**Comment by Fae6068123** [comment]
I have checked the version of locallib.php It is 14/03/22


From: Evans, Frederick
Sent: 14 March 2022 13:21
To: PlaneteStream/moodle-assignsubmission_estream ***@***.***>
Subject: RE: [PlaneteStream/moodle-assignsubmission_estream] When using eStream the footer is appearing at a fixed point on the background. (Issue #12)

Which version should be used?

**Comment by PlaneteStream** [comment]
Hi Frederick,

The file was last updated 4 months ago, so it should have a last modified date of November 18th 2021 unless custom changes have been made today. 

If you could get in touch with us at support@planetestream.co.uk providing a copy of the file and any screenshots of the issue, that would be great.

**Comment by Fae6068123** [comment]
Hi,

Yes, I just checked, it is November 11 fix I installed. V. 2021111800

Thank you

**Comment by PlaneteStream** [comment]
Hi Frederick,

Support will be in touch regarding this issue so that we can more easily identify the issue.

Thanks!
