### ISSUE TITLE
Is this source repo getting updates?

### ISSUE THREAD

**Issue by andywortman** [PlaneteStream/moodle-assignsubmission_estream#14]
Noticed that a newer version is available at https://moodle.org/plugins/assignsubmission_estream/versions.  Will that version be available in this repo as well?  Is there another source repo we should be using?

**Comment by PlaneteStream** [comment]
Hi Andy,

We often add tiny changes for specific customers that don't necessitate updating this repo, but I've gone ahead and updated it now regardless.

Thanks!

**Comment by andywortman** [comment]
Thanks for the quick response!
