### ISSUE TITLE
Privacy provider is incomplete

### ISSUE THREAD

**Issue by frederikmillingpytlick** [PlaneteStream/moodle-assignsubmission_estream#16]
The privacy provider class is incomplete and in invalid php syntax. This causes errors when running privacy provider stuff in Moodle.

**Comment by PlaneteStream** [comment]
Hi @frederikmillingpytlick ,

Could you please detail how you're deleting users? I've just attempted to delete a new user via the icon in /admin/user.php and this has gone through okay with no debug output. Can I also ask which version of Moodle you're using?

**Comment by frederikmillingpytlick** [comment]
I have no clue how to reproduce the error message in Moodle, but it is pretty clear that the following causes errors:
[classes/privacy/provider.php](https://github.com/PlaneteStream/moodle-assignsubmission_estream/blob/95dfbf1be2abe8300355602c11ae3a474c50f73d/classes/privacy/provider.php)
![image](https://github.com/PlaneteStream/moodle-assignsubmission_estream/assets/78727001/63ba9c75-2467-460c-890c-1504b57a0630)

We are using Moodle 4.2.1.

**Comment by PlaneteStream** [comment]
Hi @frederikmillingpytlick ,

Could you pull down the new file and re-test on your end? The syntax looks better now.

Strangely this file did not trigger an issue with developer debugging on, on either our 3.11 or 4.2 sites.

**Comment by frederikmillingpytlick** [comment]
@PlaneteStream it is still broken.
![image](https://github.com/PlaneteStream/moodle-assignsubmission_estream/assets/78727001/89414636-d547-48c6-873a-d18b532ee843)


1. You have 2 functions with the same name
2. You are implementing an interface, but not adding the methods it requires
3. You reference an unknown class "collection", you probably need to import it

**Comment by PlaneteStream** [comment]
Apologies @frederikmillingpytlick , the file was being uploaded from the wrong place and was incomplete.

I've corrected this and updated one of our test sites, no error messages are present and I can remove a student's submission as expected without issue.

Are there any issues on your end?

**Comment by frederikmillingpytlick** [comment]
Seems ok now, I will let you know if anything happens :)
