### ISSUE TITLE
eStream submission causes a bug so that submission status doesn't change.

### ISSUE THREAD

**Issue by Jarvil** [PlaneteStream/moodle-assignsubmission_estream#4]
eStream submission causes a bug that submission status doesn't change.
![estream1](https://cloud.githubusercontent.com/assets/15193418/24740396/aa10fe1c-1aa9-11e7-952c-ca6d536b3b43.PNG)
![estream2](https://cloud.githubusercontent.com/assets/15193418/24740408/ad343190-1aa9-11e7-9802-7b39543ae75e.PNG)

**How to repeat**

1. Create assingment
2. Enable audio/video -submission, file submission and online text submission types
3. Save and return to course
4. Log in as student
5. Open the assignment
6. Note that Submission status is "no attempt"
7. Click "add submission"
8. Only add text and file submission, do not add any planet estream submission.
9. Click "save changes"
10. Notice how the page doesn't change, it just tried to display error which is not displayed, you can only see red bar that you can close with X-button. Even with full debug and show error message no error is displayed.
11. Now if you return to the course by clicking the course name you can see your file and text have been submitted but the "Submission status" is still "No attempt". Also when viewing the submission as a teacher it shows in the Status-row "no submission"

This concerns Moodle 3.1.5+ (Build: 20170316) assignsubmission_estream version 6.23
2017012600

**Comment by PlaneteStream** [comment]
Hi Jarvil,

Thanks for reporting this to us. It will be investigated soon, after other emergency development work is complete. We are also planning a rewrite of the plugin to bring it more in-line with our current interface and other Moodle plugins.

**Comment by PlaneteStream** [comment]
Hi Jarvil,

I've just put up a 6.35 release of this plugin on the Moodle plugin repository. I've tested some changes this morning and assignments will now be marked as submitted even when no eStream video is uploaded. Please feed back on whether this is working for you. Turning on debugging will still result in an error but as far as I can see, this does not affect the submission, and we have other high priority projects to work on first and foremost. 

This is likely to be the final update to this plugin as we are planning either a rewrite, or discontinuation in favour of the ATTO and TinyMCE plugins.
