### ISSUE TITLE
Repositories out of date

### ISSUE THREAD

**Issue by tonyjbutler** [PlaneteStream/moodle-assignsubmission_estream#5]
Any chance you could keep these plugin repos up to date, or point me somewhere else where they are maintained? I'd really like to automate updates and these eStream plugins are the last remaining ones we use that still entail messing about with zip files.

Thanks,
Tony

**Comment by PlaneteStream** [comment]
Hi Tony,

We've only ever had this repository up as it's been a requirement for Moodle, at least in the past. The latest versions of our plugins are always available at the official [Moodle plugins directory](https://moodle.org/plugins/browse.php?list=contributor&id=1519383), where you should be able to set up a direct install to your Moodle site(s) without the need to manually move the zip files.

Thanks!

**Comment by tonyjbutler** [comment]
Thanks for getting back to me but unfortunately it's not that simple. We have a CI/CD pipeline with all plugins maintained as Git submodules. This stands up docker containers for dev, testing, load testing etc. with various releases of Moodle code and plugins baked in. I think the solution you suggest would bypass that process and just deploy plugins directly to the web hosts (correct me if I'm wrong).

**Comment by PlaneteStream** [comment]
Hi Tony,

In this instance the Moodle plugin is available on GitHub to satisfy the Moodle Plugins listing requirements only. The reason we do not update the plugin on GitHub is that our plugins often depend on also having the latest version of Planet eStream installed simultaneously. This means an automatic deployment method may leave people with non-functional integrations if they’re unaware of that aspect.

**Comment by tonyjbutler** [comment]
Well, actually the plugin isn't available via GitHub -- only an outdated release of it is -- so if that is a requirement, it isn't being satisfied.

Any inter-dependencies between the plugins and the eStream version installed should be handled by the plugin code itself, e.g. by automatically disabling incompatible features based on the version detected. There's nothing to stop an admin downloading the latest releases of the plugins as zip files and breaking their integration manually; the method of deployment is irrelevant.

**Comment by PlaneteStream** [comment]
Just to clarify, in this case the Moodle Plugin listings originally made it a requirement to have a link to a VCS. Without it the posting could not be submitted, therefore we satisfied that requirement and advise our customers to update manually.

Please note that in all cases our support team provide assistance at the time of installation and setup of a customers’ Planet eStream instance. This includes guidance on setting up the Moodle integrations where required. We also provide support to customers during any updates to Moodle plugins to assist them in ensuring they have the correct versions. 

We have now updated the plugins on the repository. However, we advise that you still check the release notes, as currently the Moodle plugins do not include version detection. If you would like to see this you can submit a request to our support team at support@planetestream.co.uk

**Comment by tonyjbutler** [comment]
Thanks. Much appreciated.
