### ISSUE TITLE
Exception - Call to undefined function profile_load_data()

### ISSUE THREAD

**Issue by tonyjbutler** [PlaneteStream/moodle-assignsubmission_estream#6]
This seems to have been introduced in version 6.5.0, although it's difficult to tell from the limited git history available in this repo.

Also could I request yet again that this repo be kept up to date please. I can see from https://moodle.org/plugins/pluginversions.php?plugin=assignsubmission_estream that version 6.5.2 has now been released, possibly including a fix for this bug, but it isn't available here. Is there an upstream repo containing all commits that I should be using instead? A changelog would also be helpful.

From our cron log:
```
Default exception handler: Exception - Call to undefined function profile_load_data() Debug: 
Error code: generalexceptionmessage
* line 259 of /mod/assign/submission/estream/locallib.php: Error thrown
* line 771 of /mod/assign/locallib.php: call to assign_submission_estream->delete_instance()
* line 56 of /mod/assign/lib.php: call to assign->delete_instance()
* line 1194 of /course/lib.php: call to assign_delete_instance()
* line 66 of /course/classes/task/course_delete_modules.php: call to course_delete_module()
* line 187 of /lib/cronlib.php: call to core_course\task\course_delete_modules->execute()
* line 74 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 61 of /admin/cli/cron.php: call to cron_run()
```
Thanks,
Tony

**Comment by PlaneteStream** [comment]
The version 6.5.2 changes have now been uploaded to this repository, which should handle the above error.
