### ISSUE TITLE
Redirecting to frontpage after a video is submitted and the assignment is saved

### ISSUE THREAD

**Issue by superfoght** [PlaneteStream/moodle-assignsubmission_estream#7]
Hi,

I have a problem with the plugin, where the students try to submit a video in an assignment. Everything is working fine, until the video is uploaded. Then the iframe showing the upload options, redirects you to the frontpage.

If you then save the submitted assignment, you get an error about your session being expired. 

The error seems to only come in Chrome and Edge. It works as intended in Firefox.

**Comment by PlaneteStream** [comment]
Hi superfoght,

Apologies on the delayed Github be I believe you contacted our support team who gave you a potential solution to the issue as we believe it's eStream-side and not the plugin. I'll go ahead and close this, please do get in touch with support@planetestream.co.uk if any issues persist.

**Comment by superfoght** [comment]
Yes, thanks for your reply.
