### ISSUE TITLE
XMLDB_TYPE_CHAR in install.xml is too long

### ISSUE THREAD

**Issue by hugoacfs** [PlaneteStream/moodle-assignsubmission_estream#8]
The limit for XMLDB_TYPE_CHAR in install.xml should not exceed 1333, otherwise it will break the installation process. The length should match the upgrade.php script for both cdid field and embedcode field.

![image](https://user-images.githubusercontent.com/47332377/123617340-0bd3e300-d7ff-11eb-9164-9470be365b3f.png)

This could be easily fixed please see [this comment](https://github.com/PlaneteStream/moodle-assignsubmission_estream/commit/3baeeb97374ff94d620e0dcb1f8d231d757c4a86#commitcomment-52750802).

**Comment by PlaneteStream** [comment]
Hi hugoacfs,

Thanks for bringing this to our attention, the XML file had not been properly updated. This has been fixed now. Please retry with the updated file.
