### ISSUE TITLE
Footer section Appearing half way down submission screen

### ISSUE THREAD

**Issue by Fae6068123** [PlaneteStream/moodle-assignsubmission_estream#9]
A known bug has been recorded, which occurs when users submit a video, the footer section appears half way down the submit screen. this issue did not exist in v.3.8 however has been introduced in version 3.10

**Comment by Fae6068123** [comment]
![image](https://user-images.githubusercontent.com/59917516/125602296-5c357273-f52c-400a-91fb-4c2eae2000ae.png)
the screen shot shows the footer section is incorrectly appearing in front of the submit screen.

**Comment by PlaneteStream** [comment]
Hi @Fae6068123,

Please send a support ticket request to support@planetestream.co.uk with the above information, as this looks more like an eStream-side problem than one with the plugin.

Thank you
